AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      Description: Code change 22345
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /
            Method: GET
      CodeUri: s3://git-to-amazon-s3-test-stack-outputbucket-1sj41gb4c8ct4/master/3349549b162772e3226e285ac6f52e256519e81a_test-pipeline.zip
