AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: s3://test-git-to-s3-outputbucket-bbqnd0b4tkpf/master/test-pipeline.zip
  MyLambdaFunctionOne:
    Type: AWS::Serverless::Function
    Properties:
      Handler: my_lambda01.lambda_handler
      Runtime: python3.7
      CodeUri: s3://test-git-to-s3-outputbucket-bbqnd0b4tkpf/master/test-pipeline.zip
  MyLambdaFunctionTwo:
    Type: AWS::Serverless::Function
    Properties:
      Handler: my_lambda02.lambda_handler
      Runtime: python3.7
      CodeUri: s3://test-git-to-s3-outputbucket-bbqnd0b4tkpf/master/test-pipeline.zip
