AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      Code: 
        S3Bucket: git-to-amazon-s3-test-stack-outputbucket-1sj41gb4c8ct
        S3Key: master/test-pipeline.zip
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /
            Method: GET
