AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LambdaCommitFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      Description: Code change 01
      CodeUri: s3://git-to-amazon-s3-outputbucket-o2zxmem5qlpa/master/test-pipeline.zip
